apps/apartaments/urls.py
from django.conf.urls import *

urlpatterns = patterns('apartaments.views',
    url(r'^$', 'apartaments_list', name='apartaments_list'),
    url(r'^search$', 'apartaments_free_list', name='apartaments_free_list'),
    url(r'^(?P<slug>[-\w]+)$', 'apartament_detail', name='apartament_detail'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView


admin.autodiscover()
urlpatterns = patterns('',
    url(r'^ajax/',include('apps.cms_plugins.contact_form.urls', namespace='ajax')),
    url(r'^zohoverify/verifyforzoho.html$', TemplateView.as_view(template_name='verify/verifyforzoho.html')),

    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^admin/', include(admin.site.urls)),


)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
                 # + static('/pl/', document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns('',
    url(r'^thanks/$', TemplateView.as_view(template_name='cms/sites/thanks.html')),
    url(r'^reservation/',include('apps.reservation.urls',namespace='reservation')),
    url(r'^apartaments/',include('apps.apartaments.urls',namespace='apartaments')),
    url(r'^', include('cms.urls')),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^ajax/',include('cms_plugins.contact_form.urls', namespace='ajax')),
    url(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
    url(r'^admin/', include(admin.site.urls)),


)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns('',
    url(r'^reservation/',include('reservation.urls',namespace='reservation')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

apps/apartaments/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from adminsortable.models import Sortable
from adminsortable.fields import SortableForeignKey
from tinymce.models import HTMLField
import reservation.models


class Apartament(Sortable):

    name = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    rooms = models.IntegerField()
    maxPeople = models.IntegerField()
    surface = models.IntegerField()

    teaserText = HTMLField(_('teaserText'))
    description = HTMLField(_('Description'))

    teaserPicture = models.ImageField(_('Teaser Picture'), upload_to='apartaments')

    published = models.BooleanField(_('Published'), default=True)

    class Meta(Sortable.Meta):
        verbose_name = _('Apartament')
        verbose_name_plural = _('Apartaments')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = self.slug.lower()
        super(Apartament, self).save(*args, **kwargs)

class Photos(Sortable):
    apartament = SortableForeignKey(Apartament, related_name='slides',
                               verbose_name=_('Gallery'))

    published = models.BooleanField(_('Published'), default=True)

    imageField1 = models.ImageField(_('Image'), upload_to='apartaments',
                                    blank=True)
    imageField2 = models.ImageField(_('Image'), upload_to='apartaments',
                                    blank=True)
    imageField3 = models.ImageField(_('Image'), upload_to='apartaments',
                                    blank=True)

    template = models.CharField(max_length=255, choices=(('1', 'one photo'),
                                                         ('2', 'two photo'),
                                                         ('3', 'three photo')
    ))

    class Meta(Sortable.Meta):
        verbose_name = _('Photo')
        verbose_name_plural = _('Photos')

    def __unicode__(self):
        return self.apartament.name

apps/reservation/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from adminsortable.models import Sortable
from adminsortable.fields import SortableForeignKey
from reservation.html_calendar import PriceHTMLCalendar
from apartaments.models import Apartament
from django.core.mail import send_mail

def formatted_price(price):
    price = str(price)
    if price.endswith('.00'):
        return price[:-3]
    return price


class Contact(Sortable):
    apartament = SortableForeignKey(Apartament, related_name='Apartament',
                               verbose_name=_('Apartament'))
    last_name = models.CharField(_('Contact person'), max_length=200, blank=True)
    start_date = models.DateTimeField(_('Booking from *'),)
    end_date = models.DateTimeField(_('Booking to *'), )
    client_email_address = models.EmailField(_('E-mail'), max_length=60,
                                             blank=True, null=True)
    phone = models.DecimalField(_('Phone'), max_digits=12, decimal_places=0 )
    created_date = models.DateTimeField(auto_now_add=True)
    personal_data = models.BooleanField(_('I agree to the processing of personal data'))
    confirmation_data = models.BooleanField(_('Confirmation of data'))
    confirmation_payment = models.BooleanField(_('Confirmation of payment'))

    class Meta:
        verbose_name = u'Rezerwacja'
        verbose_name_plural = u'Rezerwacje'

    def save(self, *args, **kwargs):
        if self.id:
            old_reservation = Contact.objects.get(pk=self.id)
            if(old_reservation.confirmation_data == False and self.confirmation_data == True):
                send_mail(u'Confirmation of Data Veriyfication',u'Thanks, your data is beeing processed', settings.DEFAULT_FROM_EMAIL, [self.client_email_address, ]+settings.CONTACT_EMAIL_TO)
            if(old_reservation.confirmation_payment == False and self.confirmation_payment == True):
                send_mail(u'Confirmation of Payment Veriyfication',u'We are waiting for your arrival', settings.DEFAULT_FROM_EMAIL, [self.client_email_address, ] + settings.CONTACT_EMAIL_TO)
        super(Contact, self).save(*args, **kwargs)


class CalendarDayManager(models.Manager):
    def get_by_date(self, year, month, slug):
        return self.all().filter(date__year=year, date__month=month, apartament__slug=slug)

    def get_html_calendar(self, year, month, slug):
        prices = self.get_by_date(year=year, month=month, slug=slug)
        try:
            settings = PriceSettings.objects.get(apartament__slug=slug)
        except:
            settings = None
        return PriceHTMLCalendar(prices, settings, slug).formatmonth(year, month)


class CalendarDay(Sortable):
    apartament = SortableForeignKey(Apartament, related_name='calendar',
                               verbose_name=_('calendar'))
    date = models.DateField(u'Data')
    price = models.DecimalField(u'Cena', max_digits=10, decimal_places=2)
    STATE_FREE = 1
    STATE_BOOKING = 2
    STATE_UNAVAILABLE = 3
    STATE_CHOICES = (
        (STATE_FREE, _('Free')),
        (STATE_BOOKING, _('Booking')),
        (STATE_UNAVAILABLE, _('Unavailable')),
    )
    state = models.PositiveSmallIntegerField(u'Stan', choices=STATE_CHOICES,
                                             default=STATE_FREE)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    objects = CalendarDayManager()

    class Meta:
        ordering = ('-date',)
        verbose_name = u'Dzień kalendarza'
        verbose_name_plural = u'Dni kalendarza'
        unique_together = ('apartament', 'date')

    def __unicode__(self):
        return str(self.date)

    @property
    def formatted_price(self):
        return formatted_price(self.price)


class PriceSettings(Sortable):
    apartament = SortableForeignKey(Apartament, related_name='price',
                               verbose_name=_('price'), unique=True)
    price = models.DecimalField(u'Cena', max_digits=10, decimal_places=2)
    show_default_price = models.BooleanField(u'Pokazuj domyślną cenę',
                                             default=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'Cena domyślna'
        verbose_name_plural = u'Cena domyślna'

    @property
    def state(self):
        return CalendarDay.STATE_FREE

    def get_state_display(self):
        return unicode(dict(CalendarDay.STATE_CHOICES)[self.state])

    @property
    def formatted_price(self):
        return formatted_price(self.price)

apps/apartaments/views.py
import datetime
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404

from .models import Apartament, Photos
from reservation.models import CalendarDay
import datetime

__author__ = 'wojtek'


def apartaments_list(request):
    # pobac z modeli elementy
    apartaments = Apartament.objects.all()
    context = {'apartaments': apartaments}
    return TemplateResponse(request, 'apartaments.html', context=context)


def apartaments_free_list(request):
    start = request.GET.get('arrival')
    end = request.GET.get('comingback')
    persons = request.GET.get('persons')

    if (start == None or end == None or persons == None):
        return apartaments_list(request)

    aparamentOCCUPIED = CalendarDay.objects.all().filter(date__range=[start, end], state=2)
    apartaments = Apartament.objects.all().filter(maxPeople__gte=persons)

    for occupied in aparamentOCCUPIED:
        apartaments = [apatament for apatament in apartaments if apatament.name != occupied.apartament.name]

    d1 = datetime.datetime.strptime(start, '%Y-%m-%d').date()
    d2 = datetime.datetime.strptime(end, '%Y-%m-%d').date()
    duration = d2 - d1

    context = {'apartaments': apartaments,
               'start': start,
               'end': end,
               'duration': duration.days,
               }

    return TemplateResponse(request, 'apartaments.html', context=context)


def apartament_detail(request, slug):
    # pobrac z modeli element na podstawie sluga
    apartament = get_object_or_404(Apartament, slug=slug)

    photos = Photos.objects.filter(apartament=apartament, published=True)
    now = datetime.datetime.now()

    context = {'apartament': apartament,
               'listOfPhotos': photos,
               'calendar': CalendarDay.objects.get_html_calendar(now.year,
                                                                 now.month, slug)
               }

    return TemplateResponse(request, 'apartament.html', context=context)

templates/apartaments.html
{% extends "base.html" %}
{% load i18n cms_tags menu_tags sekizai_tags thumbnail %}

{% block extra-js %}
    {{ block.super }}
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#arival").datepicker({
                dateFormat: "yy-mm-dd",
                showOn: "button",
                buttonImage: "{{ STATIC_URL }}img/kalendarz.png",
                buttonImageOnly: true,
                showAnim: "slideDown"
            });

            $("#comingback").datepicker({
                dateFormat: "yy-mm-dd",
                showOn: "button",
                buttonImage: "{{ STATIC_URL }}img/kalendarz.png",
                buttonImageOnly: true,
                showAnim: "slideDown"
            });
        $("li.active").removeClass("active");
        $("a[href='/apartaments/']").closest("li").addClass("active");
        });
    </script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}js/libs/jquery-ui.css">
    <link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/apartaments.css">
{% endblock %}


{#{% block header %}#}
{#{% endblock %}#}

{% block contact_section %}
{% endblock %}

{% block reservation %}
    <div class="main-content">

        <div class="purchase">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="rezerwacja visible-desktop">
                            <div class="headline"><h2>{% trans "Booking" %}</h2></div>
                            <div class="rezerw_content">
                                <form action="/{{ LANGUAGE_CODE|lower }}/apartaments/search"
                                      method="GET">
                                    <p>{% trans "Arrival" %}</p>
                                    <input type="text" name="arrival" id="arival"/>

                                    <p>{% trans "Check out" %}</p>
                                    <input type="text" name="comingback"
                                           id="comingback"/>

                                    <div class="col-md-8 form-group" style="margin-left: -15px">
                                        <label class="control-label  "
                                               for="id_persons">{% trans "Number of persons" %}</label>
                                        <select class="form-control" id="id_persons" name="persons">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4" selected>4</option>
                                            <option value="5">5</option>
                                            <option value="6">6</option>
                                        </select>
                                    </div>
                                    <div class="clearfix"></div>

                                    <button class="btn-u btn-u-green" type="submit">
                                        {% trans "check availability" %}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>


                    <div class="col-md-9 apartamenty">

                        {% for apartament in apartaments %}

                            <div class=" panel panel-default">
                                <div class="panel-heading">
                                    <h2>
                                        <a href="{% url "apartaments:apartament_detail" apartament.slug %}">
                                            <div class="title">{{ apartament.name }}</div>
                                        </a>
                                    </h2>
                                    <div class="subtitle">{{ apartament.subtitle }}</div>

                                </div>
                                <div class="panel-body">
                                    <div class="row">

                                        <div class="col-md-9">
                                            <div class="aboutText">{{ apartament.teaserText }}</div>
                                            <div class="headline"><h2>{% trans "Details" %}</h2></div>

                                            <div class="span4 liczbapokoi">
                                                <div>{% trans "Rooms" %}: {{ apartament.rooms }}</div>
                                                <div>{% trans "Max people" %}: {{ apartament.maxPeople }}</div>
                                                <div>
                                                    {% trans "Surface" %}: {{ apartament.surface }}
                                                    m2
                                                </div>
                                                {% trans "Prices" %}:
                                                {% for price in apartament.price.all %}
                                                    {{ price.price }} {% trans "$" %}<br>{% endfor %}
                                            </div>
                                        </div>
                                        <div class="col-md-3 pull-right">
                                            <img src="{% thumbnail apartament.teaserPicture 197x300 crop %}" alt=""/>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-footer">
                                    <a class="btn btn-buy"
                                       href="/{{ LANGUAGE_CODE|lower }}/reservation/?name={{ apartament.pk }}{% if start and end %};start={{ start }};end={{ end }}{% endif %}">
                                        <div class="span4 lookup">
                                            {% trans "Book" %}
                                        </div>
                                    </a>
                                </div>
                            </div>



                        {% endfor %}


                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/contact_plugin.html
{% load i18n thumbnail picture_apartament %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}js/libs/jquery-ui.css">
<script>
    (function ($) {
        $(function () {
            $("#id_start_date").datepicker({ showOptions: {direction: 'up'}, minDate: 0, maxDate: "+1Y", dateFormat: 'yy-mm-dd', firstDay: 1, dayNames: ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'], dayNamesMin: ['Nd', 'Po', 'Wt', 'Śr', 'Cz', 'Pt', 'So'], monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzeszień', 'Październik', 'Listopad', 'Grudzień'], monthNamesShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru']});
            $("#id_end_date").datepicker({ showOptions: {direction: 'up'}, minDate: 0, maxDate: "+1Y", dateFormat: 'yy-mm-dd', firstDay: 1, dayNames: ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'], dayNamesMin: ['Nd', 'Po', 'Wt', 'Śr', 'Cz', 'Pt', 'So'], monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzeszień', 'Październik', 'Listopad', 'Grudzień'], monthNamesShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru']});
        });
    })(jQuery)
</script>

<div class="smalest-container reserv">
    <div class="row-fluid">
        <div class="span12 title text-center">
            <div class="plugin_title">
                <h3>{% trans "Book your apartment" %}</h3>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6 form">
            {% if form %}
                <form action="" method="post" id="reservation"
                      class="form-horizontal">
                    {% csrf_token %}
                    {{ form }}
                    <div class="buttonHolder ">
                        <input type="submit" name="submit"
                               value="{% blocktrans %}Send{% endblocktrans %}"
                               class="primaryAction"/>
                    </div>
                </form>
            {% else %}
                <div class="alert alert-success">
                    {% trans "Thank you message has been sent" %}
                </div>
            {% endif %}


            <div class="plugin_contact">
                <p>{% trans "If you selected date the apartment is already booked, it will be suggested to you another closest to date." %}</p>
            </div>
        </div>
        <div class="span6 form">
            <a href="{% if apartament %}{% url "apartaments:apartament_detail" apartament.slug %}{% endif %}" class="mask" target="_blank">
                                    <img src="{{ MEDIA_URL }}{% picture pk %}">
                                    {% if end and start %}
                                            <span class="caption fade-caption">
                                                    {% trans "From" %}: {{ start }}
                                                    <br>{% trans "To" %}: {{ end }}
                                                    <br>{% trans "Duration" %}: {{ duration }}
                                            <h4>{% trans "Price of accommodation" %}</h4>
                                            <h5>{% trans "HIGH SEASON" %}</h5>
                                            {% with apartament.priceHigh as priceHigh %}
                                            <p>{% widthratio priceHigh 1 duration %}{% trans "$" %}</p>
                                            {% endwith %}
                                            <h5>{% trans "LOW SEASON" %}</h5>
                                            {% with apartament.priceLow as priceLow %}
                                            <p>{% widthratio priceLow 1 duration %}{% trans "$" %}</p>
                                            {% endwith %}
                                            </span>
                                    {% endif %}
            </a>

        </div>
    </div>
</div>